spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=1475963
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Nivel de logging para el paquete
logging.level.com.example.demo=INFO
# Archivo de logs
logging.file.name=logs/app.log
